name: Create Release with Compiled Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [
            x86_64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
            aarch64-unknown-linux-gnu,
            aarch64-unknown-linux-musl,

            aarch64-pc-windows-msvc
            x86_64-pc-windows-msvc,

            aarch64-apple-darwin
            x86_64-apple-darwin,
          ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          toolchain: stable

      - name: Install target platform
        run: rustup target add ${{ matrix.target }}

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir -p releases
          cp target/${{ matrix.target }}/release/zksync-upgrade-verify releases/zksync-upgrade-verify-${{ matrix.target }}-${{ github.ref_name }}

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binary
          path: releases/zksync-upgrade-verify-${{ matrix.target }}-${{ github.ref_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          path: releases

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Release for version ${{ github.ref_name }}"

      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*
          token: ${{ secrets.GITHUB_TOKEN }}
